[frames]
[frames.134]
tags = [
{name="so", data={sound_file="Paul/palanquin/drop.wav"}}, 
]
[frames.51]
tags = [
{name="so", data={sound_file="Paul/palanquin/footsteps/in/step4.wav"}}, 
]

[frames.1]
tags = [
{name="so", data={sound_file="Paul/palanquin/footsteps/in/step1.wav"}}, 
]

[frames.68]
tags = [
{name="so", data={sound_file="Paul/palanquin/footsteps/in/step5.wav"}}, 
]

[frames.34]
tags = [
{name="so", data={sound_file="Paul/palanquin/footsteps/in/step3.wav"}}, 
]

[frames.17]
tags = [
{name="so", data={sound_file="Paul/palanquin/footsteps/in/step2.wav"}}, 
]

