@echo off
echo OLE 2.1.0 update cleanup ready to start. Please ensure to run this before merging the new files.
pause
echo .

echo Cleaning up deprecated folders...

RD /S /Q "base\characters\Ryunosuke\"
RD /S /Q "base\characters\Ryunosuke_Badgeless\"
RD /S /Q "base\characters\Ryunosuke_DLC\custom_objections\"
RD /S /Q "base\characters\PhoenixDD_Sweater\(b)\Wit\Classic\"
RD /S /Q "base\characters\PhoenixDD_Sweater\(b)\Wit\Sweater\"
RD /S /Q "base\characters\PhoenixDD\(a)\Def\Classic\"
RD /S /Q "base\characters\PhoenixDD\(a)\Def\Sweater\"
RD /S /Q "base\characters\PhoenixDD\(b)\Def\Classic\"
RD /S /Q "base\characters\PhoenixDD\(b)\Def\Sweater\"
RD /S /Q "base\characters\PhoenixDD\(a)\Wit\Classic\"
RD /S /Q "base\characters\PhoenixDD\(a)\Wit\Sweater\"
RD /S /Q "base\characters\PhoenixDD\(b)\Wit\Classic\"
RD /S /Q "base\characters\PhoenixDD\(b)\Wit\Sweater\"
RD /S /Q "base\characters\PhoenixDD\anim\Def\Classic\"
RD /S /Q "base\characters\PhoenixDD\anim\Def\Sweater\"
RD /S /Q "base\characters\PhoenixDD\anim\Wit\Classic\"
RD /S /Q "base\characters\PhoenixDD\anim\Wit\Sweater\"
RD /S /Q "base\characters\ApolloSOJ\emotions\"
RD /S /Q "base\sounds\general\Joan Garrideb\"
RD /S /Q "base\sounds\general\Andistandhin\"
RD /S /Q "base\characters\Tonate\(a)\bomb_overlay\"
RD /S /Q "base\characters\Tonate\(b)\bomb_overlay\"
RD /S /Q "base\characters\Gina\"
RD /S /Q "base\characters\Uendo\"
RD /S /Q "base\sounds\general\Uendo\"
RD /S /Q "base\sounds\general\Armie\"
RD /S /Q "base\misc\Tonate\"
RD /S /Q "base\sounds\general\Shiv\"
RD /S /Q "base\background\DDGyaxa\"
RD /S /Q "base\background\DGS2BarokOffice\"
RD /S /Q "base\background\PLvsPWDefLobbyLabyrinthia\"
RD /S /Q "base\background\PLvsPWBellTower\"
RD /S /Q "base\background\PLvsPWEclaireBakery\"
RD /S /Q "base\characters\Geiru\"
RD /S /Q "base\sounds\general\Geiru\"
RD /S /Q "base\misc\Geiru\"
RD /S /Q "base\characters\Susato_DLC\emotions\"
RD /S /Q "base\characters\Auchi_DGS2\"
RD /S /Q "base\characters\Rayfa\"
RD /S /Q "base\characters\Orla\"
RD /S /Q "base\characters\MayaPLvsPW\"
RD /S /Q "base\characters\Maiday\"
RD /S /Q "base\sounds\general\Maiday\"
RD /S /Q "base\characters\Blackquill\custom_objections\"
RD /S /Q "base\characters\Blackquill_ChainBreak\custom_objections\"
RD /S /Q "base\characters\Blackquill_Unchained\custom_objections\"
RD /S /Q "base\characters\AthenaSOJ\anim\co\matrix\swipe\"
RD /S /Q "base\characters\AthenaSOJ\anim\def\matrix\matrixstartup\"
RD /S /Q "base\characters\AthenaSOJ\anim\def\matrix\matrixswipe\"
RD /S /Q "base\characters\AthenaSOJ\emotions\"
RD /S /Q "base\characters\Merlin\emotions\"

echo Deprecated folders removed.
echo .

echo Cleaning up deprecated files...

DEL "base\characters\Ryunosuke_DLC\custom.wav"
DEL "base\characters\PhoenixSOJ_Sengoku\(a)\handsondesk.webp"
DEL "base\characters\PhoenixSOJ_Sengoku\(b)\handsondesk.webp"
DEL "base\characters\William\(a)\desktop.ini"
DEL "base\characters\William\(b)\desktop.ini"
DEL "base\sounds\general\William\william-problem.opus"
DEL "base\characters\Graydon\objection.opus"
DEL "base\characters\Graydon\custom.opus"
DEL "base\characters\ApolloSOJ\(a)\zoom.gif"
DEL "base\characters\ApolloSOJ\(b)\zoom.gif"
DEL "base\characters\Dhurke\iniswaps.ini"
DEL "base\characters\Susato_DLC\anim\book_anim.webp.toml"
DEL "base\characters\Susato_DLC\anim\book_animco.webp.toml"
DEL "base\characters\Susato_DLC\anim\book_idea_post.webp.toml"
DEL "base\characters\Susato_DLC\anim\book_idea_postco.webp.toml"
DEL "base\characters\Susato_DLC\anim\book_idea_pre.webp.toml"
DEL "base\characters\Susato_DLC\anim\book_idea_preco.webp.toml"
DEL "base\characters\Susato_DLC\anim\book_post.webp.toml"
DEL "base\characters\Susato_DLC\anim\book_postco.webp.toml"
DEL "base\characters\Susato_DLC\anim\book_pre.webp.toml"
DEL "base\characters\Susato_DLC\anim\book_preco.webp.toml"
DEL "base\characters\Susato_DLC\anim\jr1_pre.webp.toml"
DEL "base\characters\Susato_DLC\anim\shock_pre.webp.toml"
DEL "base\characters\Susato_DLC\anim\shock_preco.webp.toml"
DEL "base\characters\Susato_DLC\anim\suggestion_pre.webp.toml"
DEL "base\characters\Garrideb\desktop.ini"
DEL "base\characters\Fabien\anim\predamage.webp.toml"
DEL "base\characters\Fabien\anim\predie.webp.toml"
DEL "base\characters\Fabien\anim\preside.webp.toml"
DEL "base\characters\Fabien\anim\twirltn.webp.toml"
DEL "base\characters\Fabien\anim\Twirl-To-Glasses.webp.toml"
DEL "base\characters\Soseki\desktop.ini"
DEL "base\characters\Wagahai\(a)\desktop.ini"
DEL "base\characters\Wagahai\(b)\desktop.ini"
DEL "base\sounds\general\sfx-rumba-pop.opus"
DEL "base\characters\Sithe\(a)\desktop.ini"
DEL "base\characters\Sithe\(b)\desktop.ini"
DEL "base\characters\Nosa\custom.apng"
DEL "base\characters\Nosa\custom.opus"
DEL "base\sounds\general\Gotts\surprise1.opus"
DEL "base\sounds\general\Gotts\surprise2.opus"
DEL "base\characters\Gotts\custom.apng"
DEL "base\characters\Gotts\custom.opus"
DEL "base\sounds\general\Burley\surprise.opus"
DEL "base\characters\Hugh\objection.opus"
DEL "base\characters\Andistandhin\Thumbs.db"
DEL "base\characters\Garan\Thumbs.db"
DEL "base\characters\Datz\desktop.ini"
DEL "base\characters\PerceiveDD\(a)\normal.png"
DEL "base\characters\PerceiveDD\(b)\normal.png"
DEL "base\characters\Apollo\anim\perceivecomplete.apng"
DEL "base\characters\Apollo\anim\perceivefadeout.apng"
DEL "base\characters\Apollo\anim\perceiveintro.gif"
DEL "base\characters\Apollo\(a)\light.gif"
DEL "base\characters\Apollo\(a)\perceive.gif"
DEL "base\characters\Apollo\(b)\light.gif"
DEL "base\characters\Apollo\(b)\perceive.gif"
DEL "base\characters\ApolloDD\custom_objections\Super Objection.gif"
DEL "base\characters\ApolloDD_Casual\custom_objections\Super Objection.gif"
DEL "base\characters\ApolloSOJ\custom_objections\Super Objection.gif"
DEL "base\characters\AthenaSOJ\custom_objections\Super Objection.gif"
DEL "base\characters\PhoenixDD\custom_objections\Super Objection.gif"
DEL "base\characters\PhoenixDD_Classic\custom_objections\Super Objection.gif"
DEL "base\characters\PhoenixDD_Sweater\custom_objections\Super Objection.gif"
DEL "base\characters\PhoenixSOJ\custom_objections\Super Objection.gif"
DEL "base\characters\PhoenixSOJ_Furio\custom_objections\Super Objection.gif"
DEL "base\characters\PhoenixSOJ_Pro\custom_objections\Super Objection.gif"
DEL "base\characters\PhoenixSOJ_Sengoku\custom_objections\Super Objection.gif"
DEL "base\sounds\general\surprise_dgs.opus"
DEL "base\sounds\general\Gina\coat.opus"
DEL "base\sounds\general\Gina\gun-fire.opus"
DEL "base\sounds\general\Gina\gun-lock.opus"
DEL "base\sounds\general\Gina\gun-lock-fire.opus"
DEL "base\sounds\general\Gina\gun-stance.opus"
DEL "base\sounds\general\Gina\problem.opus"
DEL "base\characters\Kay\(a)\Default\hips.gif"
DEL "base\characters\Kay\(b)\Default\hips.gif"
DEL "base\sounds\general\Ahlbi\search.opus"
DEL "base\characters\Tusspells\anim\down.webp"
DEL "base\characters\Tusspells\anim\forward.webp"
DEL "base\sounds\general\surprise_plvspw.opus"
DEL "base\characters\Athena2D\(a)\wit\dark.gif"
DEL "base\characters\Athena2D\(a)\wit\eyeroll.gif"
DEL "base\characters\Athena2D\(a)\wit\insane.gif"
DEL "base\characters\Athena2D\(a)\wit\murderous.gif"
DEL "base\characters\Athena2D\(a)\wit\sadistic.gif"
DEL "base\characters\Athena2D\(b)\wit\dark.gif"
DEL "base\characters\Athena2D\(b)\wit\eyeroll.gif"
DEL "base\characters\Athena2D\(b)\wit\insane.gif"
DEL "base\characters\Athena2D\(b)\wit\murderous.gif"
DEL "base\characters\Athena2D\(b)\wit\sadistic.gif"
DEL "base\characters\Athena2D\anim\wit\evillaugh.gif"
DEL "base\characters\Darklaw\(a)\witness\Belduke\crossed.gif"
DEL "base\characters\Darklaw\(a)\witness\Belduke\normal.gif"
DEL "base\characters\Darklaw\(b)\witness\Belduke\crossed.gif"
DEL "base\characters\Darklaw\(b)\witness\Belduke\normal.gif"
DEL "base\characters\Darklaw\anim\witness\Belduke\crossed_pre.gif"
DEL "base\characters\Darklaw\anim\witness\Belduke\glasses_anim.gif"
DEL "base\characters\AthenaSOJ\(b)\co\matrix\furious(1).gif"
DEL "base\characters\AthenaSOJ\(b)\co\matrix\happy(1).gif"
DEL "base\characters\AthenaSOJ\(b)\co\matrix\matrix(1).gif"
DEL "base\characters\AthenaSOJ\(b)\co\matrix\normal(1).gif"
DEL "base\characters\AthenaSOJ\(b)\co\matrix\sweat(1).gif"
DEL "base\characters\AthenaSOJ\(b)\co\matrix\thinking(1).gif"
DEL "base\characters\AthenaSOJ\(b)\co\matrix\writhe(1).gif"
DEL "base\characters\Lazarus\fistup_anim.webp"
DEL "base\characters\Lazarus\gun_anim.webp"
DEL "base\characters\Lazarus\gunspintn_anim.webp"
DEL "base\characters\Lazarus\nod_anim.webp"
DEL "base\characters\Lazarus\shake_anim.webp"
DEL "base\characters\Lazarus\shock_anim.webp"
DEL "base\characters\Lazarus\shocktn_anim.webp"
DEL "base\characters\Lazarus\slam_anim.webp"
DEL "base\characters\Lazarus\slamtn_anim.webp"
DEL "base\characters\Lazarus\sleep_anim.webp"
DEL "base\characters\Lazarus\thinking_anim.webp"
DEL "base\characters\Lazarus\thinkingtn_anim.webp"
DEL "base\characters\Lazarus\verdict_anim.webp"
DEL "base\characters\Lazarus\verdicttn_anim.webp"

echo Deprecated files removed.
echo .
echo You may now merge the updated files.
pause 