[frames]
[frames.893]
tags = [
{name="sf", data={type=196607, duration=65535}}, 
]
[frames.854]
tags = [
{name="so", data={sound_file="Paul/breakdown/breakdown4.wav"}}, 
]

[frames.578]
tags = [
{name="so", data={sound_file="Paul/telop.wav"}}, 
]

[frames.769]
tags = [
{name="sf", data={type=131071, duration=65535}}, 
{name="so", data={sound_file="Paul/breakdown/breakdown1.wav"}}, 
]

[frames.1028]
tags = [
{name="sf", data={type=131071, duration=65535}}, 
]

[frames.179]
tags = [
{name="so", data={sound_file="Paul/breakdown/breakdown2.wav"}}, 
]

[frames.134]
tags = [
{name="so", data={sound_file="Paul/breakdown/breakdown1.wav"}}, 
]

[frames.508]
tags = [
{name="sf", data={type=196607, duration=65535}}, 
]

[frames.419]
tags = [
{name="so", data={sound_file="Paul/breakdown/breakdown3.wav"}}, 
]

