[frames]
[frames.98]
tags = [
{name="so", data={sound_file="Paul/footsteps/leave/step3.wav"}}, 
]
[frames.64]
tags = [
{name="so", data={sound_file="Paul/footsteps/leave/step1.wav"}}, 
]

[frames.115]
tags = [
{name="so", data={sound_file="Paul/footsteps/leave/step4.wav"}}, 
]

[frames.81]
tags = [
{name="so", data={sound_file="Paul/footsteps/leave/step2.wav"}}, 
]

[frames.34]
tags = [
{name="so", data={sound_file="Paul/take.wav"}}, 
]

